### ISSUE TITLE
Allow configuration of connection pool size for BynderClient 

### ISSUE THREAD

**Issue by jhall234** [Bynder/bynder-python-sdk#28]
Currently, there is no way to increase the max number of connection pool used by the SDK. 

The connection pool is created by: https://github.com/psf/requests/blob/99b3b492418d0751ca960178d274f89805095e4c/requests/adapters.py#L114 (`BynderOAuth2Session` --> `requests_oauthlib.oauth2_session.OAuth2Session` --> `requests.Session` --> `requests.adapter`) which the default is set to 10 connections. 

It would be advantageous to abstract the configuration of that value to the SDK, so that bulk image uploads can be processed in a timely fashion.

**Comment by Arpit-Sharma-USC** [comment]
Hi @jhall234 thanks for reaching out to us about this. Can you please give us specifics of your request? 

From what I understand you propose we enable support to make the max connection pool configurable somehow to support values over the default value, 10.

Thanks and we look forward to your response!

**Comment by jhall234** [comment]
Yes that summary is correct. Our team is writing a service which is transitioning our digital assets to Bynder, and there are a very large amount of these assets. We would like to scale the number of available connections so that this process does not have to run for weeks on end. Even being able to double the max number of connections to 20 would significantly speed up this process. I would envision the ability to pass in a variable to the BynderClient initialization which gets passed down to be able to specify the max connection pool size. Currently to solve this problem, we are looking at trying to monkey patch the `requests.adapter` module to augment the default

**Comment by Arpit-Sharma-USC** [comment]
Hi @jhall234 I brought your concerns to the team and we discussed this through. Unfortunately, at the moment I would like to politely decline this feature request. The reason behind this is it could negatively impact bynder and it's sdk clients to a certain degree. Especially with the lack of a request throttling mechanism at our backend to handle large number of upload requests.

We are however working on a newer version of the sdks which overhauls the upload mechanism. We will look to address this concern with that release.
