### ISSUE TITLE
`asset_bank_client.upload_file` does not return anything

### ISSUE THREAD

**Issue by ilkka** [Bynder/bynder-python-sdk#3]
I was a bit surprised by this and first thought my uploads were failing silently. They did in fact succeed, and it seems that the reason `upload_file` does not return anything is that `UploadClient._save_media` doeos not return anything. It just [defines a local variable `save_success`](https://github.com/Bynder/bynder-python-sdk/blob/b738c1bec83d9aea3f87f8dd97148e6fde5d2a25/bynder_sdk/client/upload_client.py#L129) that is not used for anything. 

How can I identify the asset after upload if `upload_file` does not return anything?

**Comment by fnavarrogonzalez** [comment]
Hi @ilkka,

You are right we should return at least the mediaid. 
You can see the minimal needed modifications in https://github.com/Bynder/bynder-python-sdk/pull/4 for make it working until we fix it.

**Comment by fnavarrogonzalez** [comment]
It's merge. You receive now a dict with a key 'mediaid' included that you can use.
I'm closing this. Reopen or create a new issue if you still having issues.

**Comment by ilkka** [comment]
That was fast, thanks! 👌🏻
