### ISSUE TITLE
athentication-refresh token access with SDK

### ISSUE THREAD

**Issue by tedatkc** [Bynder/bynder-python-sdk#31]
Trying to access our Bynder instance with the python SDK.  I've tried the "getting started" and running into problems.

I've submitted a ticket 160448 and they redirected me here.

<pre>
from bynder_sdk import BynderClient

bynder_client = BynderClient(
    domain=DOMAIN,
    redirect_uri='https://localhost/callback',
    client_id=CLIENTID,
    client_secret=CLIENTSECRET
)

print(bynder_client.get_authorization_url())
code = input('Code: ')
bynder_client.fetch_token(code)

asset_bank_client = bynder_client.asset_bank_client
media_list = asset_bank_client.media_list({
    'limit': 2,
    'type': 'image'
})

# ERROR
# TypeError: Missing required arguments: ['scopes']
# 
# %%
bynder_client = BynderClient(
    domain=DOMAIN,
    redirect_uri='https://localhost/callback',
    client_id=CLIENTID,
    client_secret=CLIENTSECRET,
    scopes=['offline',
            'asset:read',
            'meta.assetbank:read'],
)

print(bynder_client.get_authorization_url())
code = input('Code: ')
bynder_client.fetch_token(code)

asset_bank_client = bynder_client.asset_bank_client
media_list = asset_bank_client.media_list({
    'limit': 2,
    'type': 'image'
})

# RESPONSE:
#    ('https://https://[MYDOMAIN]/v6/authentication/
#      oauth2/auth?response_type=code&client_id=[MYCLIENTID]&
#      redirect_uri=https%3A%2F%2Flocalhost%2Fcallback.&scope=offline+asset%3Aread+
#      meta.assetbank%3Aread&state=ElNUPvMv', 'ElNUPvMv')
#
# ENTERED CODE from state above...
#    Code: ElNUPvMv
#
# ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries 
# exceeded with url: //[MYDOMAIN]/v6/authentication/oauth2/token 
# (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 
# 0x000002FDEB40B460>: Failed to establish a new connection: [Errno 11001] 
# getaddrinfo failed'))
</pre>

**Comment by TimBloembergen** [comment]
Hi @tedatkc ,

In your bynder_client you are not passing the `scopes` parameter, which is why you get the error "Missing required arguments: ['scopes'] error.

Please have a look at our example app, https://github.com/Bynder/bynder-python-sdk/blob/088f585d9b7ff09494e283be38a9a33636e38c48/example/app.py#L40-L47

https://github.com/Bynder/bynder-python-sdk/tree/master/example

**Comment by tedatkc** [comment]
Sorry.  I wasn't very clear.  The first example from the "getting started" didn't work -- I think that warrants changes the documentation under "getting started".

A little farther down, I use the scopes argument and it still doesn't work.

<pre>
# %%
bynder_client = BynderClient(
    domain=DOMAIN,
    redirect_uri='https://localhost/callback',
    client_id=CLIENTID,
    client_secret=CLIENTSECRET,
    scopes=['offline',
            'asset:read',
            'meta.assetbank:read'],
)

print(bynder_client.get_authorization_url())
code = input('Code: ')
bynder_client.fetch_token(code)

asset_bank_client = bynder_client.asset_bank_client
media_list = asset_bank_client.media_list({
    'limit': 2,
    'type': 'image'
})

# RESPONSE:
#    ('https://https://[MYDOMAIN]/v6/authentication/
#      oauth2/auth?response_type=code&client_id=[MYCLIENTID]&
#      redirect_uri=https%3A%2F%2Flocalhost%2Fcallback.&scope=offline+asset%3Aread+
#      meta.assetbank%3Aread&state=ElNUPvMv', 'ElNUPvMv')
#
# ENTERED CODE from state above...
#    Code: ElNUPvMv
#
# ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries 
# exceeded with url: //[MYDOMAIN]/v6/authentication/oauth2/token 
# (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 11001] 
# getaddrinfo failed'))
</pre>

**Comment by tedatkc** [comment]
Since issue is closed, I don’t know if this will be seen, but including here, too:

Sorry. I wasn't very clear. The first example from the "getting started" didn't work -- I think that warrants changes the documentation under "getting started".
A little farther down, I use the scopes argument and it still doesn't work.
# %%
bynder_client = BynderClient(
    domain=DOMAIN,
    redirect_uri='https://localhost/callback',
    client_id=CLIENTID,
    client_secret=CLIENTSECRET,
    scopes=['offline',
            'asset:read',
            'meta.assetbank:read'],
)

print(bynder_client.get_authorization_url())
code = input('Code: ')
bynder_client.fetch_token(code)

asset_bank_client = bynder_client.asset_bank_client
media_list = asset_bank_client.media_list({
    'limit': 2,
    'type': 'image'
})

# RESPONSE:
#    ('https://https://[MYDOMAIN]/v6/authentication/
#      oauth2/auth?response_type=code&client_id=[MYCLIENTID]&
#      redirect_uri=https%3A%2F%2Flocalhost%2Fcallback.&scope=offline+asset%3Aread+
#      meta.assetbank%3Aread&state=ElNUPvMv', 'ElNUPvMv')
#
# ENTERED CODE from state above...
#    Code: ElNUPvMv
#
# ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries
# exceeded with url: //[MYDOMAIN]/v6/authentication/oauth2/token
# (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 11001]
# getaddrinfo failed'))
