### ISSUE TITLE
Upload file to the asset bank gives an error related to the Bad Request for url

### ISSUE THREAD

**Issue by geekbeard** [Bynder/bynder-python-sdk#33]
Using the code in the example app.py to upload a small png to the asset bank:

```
def uploadFile(asset_bank_client, brand_id, file_path):
    print('\n> Upload a file to the asset bank')
    uploaded_file = asset_bank_client.upload_file(
    file_path=file_path,
    brand_id=brand_id)
    print(uploaded_file)
```

Gives out this error:

```Upload a file to the asset bank
Traceback (most recent call last):
  File "e:\Dev\Bynder-test\main.py", line 100, in <module>
    uploadFile(asset_bank_client, 'AAAAAAA-AAAA-AAAA-AAAAAAAAAAAAAA', 'E:\\Dev\\Bynder-test\\test.png')
  File "e:\Dev\Bynder-test\main.py", line 63, in uploadFile
    uploaded_file = asset_bank_client.upload_file(
  File "E:\Dev\Bynder-test\venv\lib\site-packages\bynder_sdk\client\asset_bank_client.py", line 104, in upload_file 
    return self.upload_client.upload(
  File "E:\Dev\Bynder-test\venv\lib\site-packages\bynder_sdk\client\upload_client.py", line 21, in upload
    init_data, total_parts = self._run_s3_upload(file_path)
  File "E:\Dev\Bynder-test\venv\lib\site-packages\bynder_sdk\client\upload_client.py", line 47, in _run_s3_upload   
    response.raise_for_status()
  File "E:\Dev\Bynder-test\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bynder-public-eu-central-1.s3.amazonaws.com/
```
Brand Id replaced in the error. 

Seems like something in the SDK methods?

**Comment by TimBloembergen** [comment]
Hi @geekbeard, I just ran a quick test and I was able to successfully upload a file using the SDK. 

I used the app.py within the example app, i\m running it in Pycharm.

I set a permanent token (for ease of testing), and ran

```
print('\n> Upload a file to the asset bank')
uploaded_file = asset_bank_client.upload_file(
    file_path='image.png',
    brand_id=brands[0]['id']
)
```

**Comment by geekbeard** [comment]
Thank you @TimBloembergen  for a quick reply!

So strange... Same code. Could this be related to any type of access rights set in the system for the brandID that's being used/tried to  be uploaded to?

**Comment by geekbeard** [comment]
@TimBloembergen - we debugged further and found out where things "break".

It's within the SDK function to upload a chunk to the S3 in the `upload_client.py`:

```
    def _run_s3_upload(self, file_path):
        """ Uploads the media to Amazon S3 bucket-endpoint.
        """
        with open(file_path, 'rb') as f:
            part_nr = 0
            total_parts = math.ceil(
                os.stat(f.fileno()).st_size / MAX_CHUNK_SIZE)

            filename = file_path.rsplit('/', 1)[-1]
            build_part_data = self._init_upload(filename, total_parts)

            part_bytes = f.read(MAX_CHUNK_SIZE)
            while part_bytes:
                part_nr = part_nr + 1
                part_data = build_part_data(part_nr)
                
#BREAKS BELOW
                response = self.session.post(
                    self.upload_url,
                    files={'file': part_bytes},
                    data=part_data['multipart_params'],
                )
#BREAKS ABOVE


                response.raise_for_status()
                self._register_part(part_data, part_nr)
                part_bytes = f.read(MAX_CHUNK_SIZE)

        return part_data, total_parts
```

And it gives this error in the response even though we can use this token for getting brands, collections, etc. just fine and we have these scopes assigned:

```
scopes=[     'asset:read', 
                    'asset:write', 
                    'asset.usage:read', 
                    'asset.usage:write',
                    'collection:read',
                    'collection:write',
                    'meta.assetbank:read',
                    'meta.assetbank:write',
                    'meta.workflow:read']
```


Error:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>InvalidArgument</Code>
<Message>Unsupported Authorization Type</Message>
<ArgumentName>Authorization</ArgumentName>
<ArgumentValue>Bearer --TOKEN-IS-HERE--</ArgumentValue>
<RequestId>H1XDXSDC0WY9AXRF</RequestId>
<HostId>AQeegsUJWdrK7D84CMD*************B7sBxKnXwCB6+1t4ijXdY=</HostId>
</Error>
```

**Comment by TimBloembergen** [comment]
Hi @geekbeard , would you be able to send me your app.py file to tim.bloembergen@bynder.com? If you can also let me know on which portal you are trying to run this I can have a closer look.

**Comment by TimBloembergen** [comment]
Hi @geekbeard , we've had a closer look and when we review the error that you are receiving and I get the same error when using OAuth2. 

I'll create a ticket for the team so we can have a closer look and resolve this problem. To unblock yourself, for the time being I can suggest to use a Permanent Token https://support.bynder.com/hc/en-us/articles/360013875300-Permanent-Tokens

Permanent tokens will be deprecated in the future but until we resolve the issue surrounding OAuth2 I can suggest to use Permanent Tokens instead. When we then release a new version of the SDK where we've fixed the problem please switch back to OAuth2 again.

**Comment by geekbeard** [comment]
Thank you @TimBloembergen !! Great news!:) I mean - bad to have something buggy, but great it's caught and will be worked on:)

Thanks again! Will look into the permanent token:)

**Comment by Arpit-Sharma-USC** [comment]
Hi @geekbeard we made a release for this issue for oauth2 [here](https://pypi.org/project/bynder-sdk/1.1.5/)
Please give that a try and let us know if you face any other issues.

**Comment by geekbeard** [comment]
Just checked! Indeed it all works fine now with the SDK 1.1.5!
Thank you all for helping!
